<a href="https://colab.research.google.com/github/paty3090/AT06-Analise-de-dados/blob/main/Tratamento_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [164]:
import pandas as pd
import seaborn as se
import statistics as st

In [165]:
# Importa os dados
tempo = pd.read_csv("/content/drive/MyDrive/tempo.csv")

In [166]:
# Visualização dos dados
tempo
tempo.head(8)
tempo.tail(8)
tempo.sample(8)

   Appearance  Temperature  Humidity Wind Play
18       sols           65        96  sim  sim
9       chuva           75       650  não  sim
13      chuva           71        91  sim  não
17       sols           64        95  sim  sim
12    nublado           81        75  não  sim
4       chuva           68        80  não  NaN
11    nublado           72        90  sim  sim
0         sol           85        85  não  não

In [167]:
# Quantidades de linhas e colunas
tempo.shape

(20, 5)

In [168]:
# Dá nomes às colunas
tempo.columns = ["Aparência", "Temperatura", "Umidade", "Vento","Jogo"]

In [169]:
# Visualização os dados
tempo.head(10)

  Aparência  Temperatura  Umidade Vento Jogo
0       sol           85       85   não  não
1       sol           80       90   sim  não
2   nublado           83       86   não  sim
3     chuva           70       68   não  sim
4     chuva           68       80   não  NaN
5     chuva           79       70   sim  sim
6     menos           64       65   sim  sim
7       sol         1220       95   não  não
8       sol           65       70   não  sim
9     chuva           75      650   não  sim

In [170]:
# Mostra se existe valores nulos ou não disponíveis (NAN)
tempo.isnull().sum()

Aparência      0
Temperatura    0
Umidade        0
Vento          0
Jogo           1
dtype: int64

In [171]:
# Agrupa a coluna Umidade
tempo['Umidade'].describe()

count     20.00000
mean     112.60000
std      126.95312
min       65.00000
25%       73.75000
50%       90.00000
75%       94.25000
max      650.00000
Name: Umidade, dtype: float64

In [172]:
# Calcula a mediana da Umidade
mediana = st.median(tempo['Umidade'])
mediana

90.0

In [173]:
# Substitui os valores nulos pela mediana
'''
fillna: preenche valores ausentes (NaN).
mediana: valor que será usado para preencher os valores ausentes (NaN) na coluna "Umidade".
inplace: modificação seja feita diretamente no DataFrame original (tempo).
Se inplace=False, o método fillna() retornaria uma cópia do DataFrame com
os valores preenchidos, mas o DataFrame original não seria modificado.
'''
tempo['Umidade'].fillna(mediana, inplace=True)

<ipython-input-173-e9bb5b77d201>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  tempo['Umidade'].fillna(mediana, inplace=True)

In [174]:
# Mostra se existe valores nulos ou não disponíveis (NAN)
tempo.isnull().sum()

Aparência      0
Temperatura    0
Umidade        0
Vento          0
Jogo           1
dtype: int64

In [175]:
# Mostra se existe valores nulos ou não disponíveis (NAs) na coluna 'Umidade'
tempo['Umidade'].isnull().sum()

np.int64(0)

In [176]:
# Mostra se existe valores nulos ou não disponíveis (NAs) na coluna 'Jogo'
tempo['Jogo'].isnull().sum()

np.int64(1)

In [177]:
# Mostra se existe valores nulos ou não disponíveis (NAs) na coluna 'Aparência'
tempo['Aparência'].isnull().sum()

np.int64(0)

In [178]:
# Preenche as NAs com o valor 'Tempestade' (critério: moda)
tempo['Jogo'].fillna('Tempestade', inplace=True)

<ipython-input-178-d8b7d8067e26>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  tempo['Jogo'].fillna('Tempestade', inplace=True)

In [179]:
# Mostra se existe valores nulos ou não disponíveis (NAs) na coluna 'Jogo'
tempo['Jogo'].isnull().sum()

np.int64(0)

In [180]:
# Visualiza a coluna 'jogar' agrupada e sua quantidade
Jogo = tempo.groupby(['Aparência']).size()
Jogo

Aparência
chuva      5
menos      1
nublado    3
sol        9
sols       2
dtype: int64

In [183]:
'''Para padronizar os valores é preciso usar o método 'loc' do Pandas para
localizar e modificar valores específicos dentro do DataFrame bank.
loc[condição, coluna]
'''
# Se o valor de 'Aparência' for 'nublado', substituirá na coluna 'vento' o valor 'não'
tempo.loc[tempo['Aparência'] == 'sols', 'Aperência'] = 'sol'

In [185]:
# Visualiza a coluna 'Aperência' agrupada e sua quantidade
Aperência = tempo.groupby(['Aperência']).size()
Aperência

Aperência
sol    2
dtype: int64

In [186]:
# Mostra os dados estatísticos da 'Vento'
tempo['Vento'].describe()

count      20
unique      2
top       sim
freq       12
Name: Vento, dtype: object

In [187]:
# Localiza os dados de 'Umidade' menores que 0 e maiores que 100
tempo.loc[(tempo['Umidade'] <= 0) | (tempo['Umidade'] > 100)]

  Aparência  Temperatura  Umidade Vento Jogo Aperência
9     chuva           75      650   não  sim       NaN

In [188]:
# Calcula a mediana
mediana = st.median(tempo['Temperatura'])
mediana

70.5

In [189]:
# Substitui os valores de 'Temperatura' pela mediana
tempo.loc[(tempo['Temperatura'] <= 0) | (tempo['Temperatura'] > 120), 'Temperatura'] = mediana

<ipython-input-189-d33cc2e9fc2d>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '70.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tempo.loc[(tempo['Temperatura'] <= 0) | (tempo['Temperatura'] > 120), 'Temperatura'] = mediana

In [190]:
# Localiza os dados de 'Temperatura' menores que 0 e maiores que 120
tempo.loc[(tempo['Temperatura'] <= 0) | (tempo['Temperatura'] > 120)]

Empty DataFrame
Columns: [Aparência, Temperatura, Umidade, Vento, Jogo, Aperência]
Index: []

In [191]:
# Localiza dados duplicados pelo 'Aparência'
'''
keep=False: especifica que todas as linhas duplicadas
devem ser marcadas como True, o restante será False.
'''
tempo.loc[tempo.duplicated(['Aparência'], keep=False)]

   Aparência  Temperatura  Umidade Vento        Jogo Aperência
0        sol         85.0       85   não         não       NaN
1        sol         80.0       90   sim         não       NaN
2    nublado         83.0       86   não         sim       NaN
3      chuva         70.0       68   não         sim       NaN
4      chuva         68.0       80   não  Tempestade       NaN
5      chuva         79.0       70   sim         sim       NaN
7        sol         70.5       95   não         não       NaN
8        sol         65.0       70   não         sim       NaN
9      chuva         75.0      650   não         sim       NaN
10       sol         75.0       70   sim         sim       NaN
11   nublado         72.0       90   sim         sim       NaN
12   nublado         81.0       75   não         sim       NaN
13     chuva         71.0       91   sim         não       NaN
14       sol         61.0       92   sim         sim       NaN
15       sol         62.0       93   sim         sim       NaN
16       sol         63.0       94   sim         sim       NaN
17      sols         64.0       95   sim         sim       sol
18      sols         65.0       96   sim         sim       sol
19       sol         66.0       97   sim         sim       NaN

In [192]:
# Exlui dados duplicados pelo 'Aparência'
'''
subset='Aparência': especifica que a coluna Vento deve ser usada como referência para identificar as duplicatas.
keep='first': entre as linhas duplicadas, a primeira ocorrência será mantida e as demais serão removidas.
'last': mantém a última ocorrência e remove as demais.
False: remove todas as ocorrências das linhas duplicadas.
inplace=True: Especifica que a modificação (remoção das linhas duplicadas) deve ser feita
diretamente no DataFrame original (tempo).
inplace=False (padrão), o método retornaria uma cópia do DataFrame com as linhas duplicadas removidas,
mas o DataFrame original permaneceria inalterado.
'''
tempo.drop_duplicates(subset='Aparência', keep='first', inplace=True)

In [193]:
# Localiza dados duplicados pelo 'Aparência'
tempo.loc[tempo.duplicated(['Aparência'], keep=False)]

Empty DataFrame
Columns: [Aparência, Temperatura, Umidade, Vento, Jogo, Aperência]
Index: []

In [194]:
# Mostra a coluna Jogo agrupada
Aparência = tempo.groupby(['Aparência']).size()
Jogo

Aparência
chuva      5
menos      1
nublado    3
sol        9
sols       2
dtype: int64

In [196]:
'''
Localiza os estados fora do domínio, no caso ('sols')
e substitui por um valor específico [critério: moda (no caso, sol)]
'''
tempo.loc[tempo['Aparência'].isin(['sols']), 'Aparência'] = 'sol'

# Mostra os estados agrupados
Aparência = tempo.groupby(['Aparência']).size()
Aparência

Aparência
chuva      1
menos      1
nublado    1
sol        2
dtype: int64

In [197]:
# Calcula o desvio padrão do 'Umidade'
desvio = st.stdev(tempo['Umidade'])
desvio

12.794530081249565

In [199]:
# Localiza Umidade com o desvio padrão 2x maior
tempo.loc[tempo['Umidade'] >= 2 * desvio]

   Aparência  Temperatura  Umidade Vento Jogo Aperência
0        sol         85.0       85   não  não       NaN
2    nublado         83.0       86   não  sim       NaN
3      chuva         70.0       68   não  sim       NaN
6      menos         64.0       65   sim  sim       NaN
17       sol         64.0       95   sim  sim       sol

In [200]:
# Calcula a mediana de 'Umidade'
mediana = st.median(tempo['Umidade'])
mediana

85

In [201]:
8637195.5
# Localiza os Umidade 2x maior que o desvio padrão e substitui pela mediana
tempo.loc[tempo['Umidade'] >= 2 * desvio, 'Umidade'] = mediana

# Localiza Umidade com o desvio padrão 2x maior
tempo.loc[tempo['Umidade'] >= 2 * desvio]

   Aparência  Temperatura  Umidade Vento Jogo Aperência
0        sol         85.0       85   não  não       NaN
2    nublado         83.0       85   não  sim       NaN
3      chuva         70.0       85   não  sim       NaN
6      menos         64.0       85   sim  sim       NaN
17       sol         64.0       85   sim  sim       sol

In [202]:
# Mostra a quantidade de linhas e colunas do dataset
tempo.shape

(5, 6)